### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by teamgroove** [jjuliano/aifiles#1]
Suggestion: yesterday i wasted an hour to find a example to do exactly that, with bookmarks. Tagging / categorization and found outdated solutions and premature products. Or tutorials to do it with IBM Watson.

If one could use this solution to categorize the bookmarks, this would have a big impact on basically any user that makes use of bookmarking extensively.

My understand from the README was, that there is the need to have seperate files (i'll try later today ...), but an exported bookmarks.html file is a single file.

Could aifiles be used or extended for that usecase?

Have a nice weekend - and thank you very much for sharing this swiss-knife with us!

**Comment by jjuliano** [comment]
Thank you for your suggestions and appreciation with this project. I agree, that is a good suggestion.
Feel free to discuss any error or bugs you've encountered!
